### ISSUE TITLE
doesn't compile on MacOS 10.4

### ISSUE THREAD

**Issue by tvogt** [icebob/vue-express-mongo-boilerplate#112]
yarn gives me:

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^

```

**Comment by dimylik** [comment]
works for me on MacOS with npm install and npm run dev
